name: Build and Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm ci
        env:
          CI: true

      - name: build
        run: |
          npm run build
        env:
          CI: true

      - name: Upload built js
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/dist/prebid.js

      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

  deployStage:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Download built js from build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: mamasuncut-stage-assets
          AWS_ACCESS_KEY_ID: ${{ secrets.awsAccess }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.awsSecret }}
          AWS_REGION: 'us-east-2' # optional: defaults to us-east-1
          SOURCE_DIR: 'build/dist' # optional: defaults to entire repository
          DEST_DIR: 'js'
  deployProd:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Download built js from build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: mamasuncut-prod-assets
          AWS_ACCESS_KEY_ID: ${{ secrets.awsAccess }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.awsSecret }}
          AWS_REGION: 'us-east-2' # optional: defaults to us-east-1
          SOURCE_DIR: 'build/dist' # optional: defaults to entire repository
          DEST_DIR: 'js'
